{% set version = "0.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-imp4p
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/imp4p_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/imp4p/imp4p_{{ version }}.tar.gz
  sha256: 7cb3aac214314b5ad748952e483e7e361e608019ec42b04e1cd6d2aa111c18fd

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-iso
    - r-rcpp >=0.12.8
    - r-norm
    - r-truncnorm
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-iso
    - r-rcpp >=0.12.8
    - r-norm
    - r-truncnorm

test:
  commands:
    - $R -e "library('imp4p')"           # [not win]
    - "\"%R%\" -e \"library('imp4p')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=imp4p
  license: GPL-3
  summary: Functions to analyse missing value mechanisms and to impute data sets in the context of bottom-up MS-based proteomics.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: imp4p
# Type: Package
# Title: Imputation for Proteomics
# Version: 0.7
# Author: Quentin Giai Gianetto
# Maintainer: Quentin Giai Gianetto <quentin2g@yahoo.fr>
# Description: Functions to analyse missing value mechanisms and to impute data sets in the context of bottom-up MS-based proteomics.
# License: GPL-3
# Depends: R (>= 3.3.0), Iso, stats, truncnorm, norm
# Encoding: UTF-8
# Imports: Rcpp (>= 0.12.8)
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2018-08-10 14:32:31 UTC; Quentin
# Repository: CRAN
# Date/Publication: 2018-08-10 15:20:02 UTC
