travis:
  secure:
    BINSTAR_TOKEN: CPRbVWYLgcuxWy6gZqj9ebXT+HDc8qSc7r5WehzFv/sar8PuvtdXboO3dLv/Ihv6milWRzQowyW5Z9ODR1ke7U22X3zhO8f/WkDLN6HZrEusB2TRSH3FLiaJth/gGzovl5AZo/JFgY1vi1aSp/rzU3ynOLuPFe6KUl3GoYd9BIHydz0EGaMvyiQ1/3SdiSPf/8c/7xJECMk2DRe4bX57krcTHCB0Kk6IOtpHv5tReIPWqlptPQCyUP9lBkDvEKCgSU8EQUUoWICQe+KBw30oTozw8IUwngl2qKDk4Goz9S0/XtrTRZ4FNZhA198+JuPD7yvOuGpLafqlzizkqLUBulFW0E2XAyFRr/+a2fcLRjyMA/mqnVmkxBTXwiyvdQ4TM2/zOSpFl6nEewfdQJLn+LmrW3T2TlnUcOKEjVaUH8toCh97tbaIvXLoa5kTppSBpRsQkdAvb6az0IvTEc6I+qY2meyY4EYzjGsXDF3l5acvzlEPAqZXugqftdoi1cwvIg1jqzGAwfs/1ILxCo1kvvVF0MycLJBiuT542Fx6HMJPte63H5gSgQ/OcE2RFaWGKtsul8T0KiRON1SYi/mUSrMh5bNKs6Ckdyhu1KllellChkgxzuCEgoS5jeOQURrOVSPCQBVK8DGXeQtf4fRdbTK5Vl/Gzy1N1FQBM84Pzpg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
